newsfeed.addFeed("Daniel L Sussman", "https://arxiv.org/a/sussman_d_1.atom2","atom")
newsfeed.addFeed("Karl Rohe", "https://arxiv.org/a/rohe_k_1.atom2","atom")
newsfeed.addFeed("Alexander Volfovsky", "https://arxiv.org/a/volfovsky_a_1.atom2","atom")
newsfeed.addFeed("Miklos Racz","https://arxiv.org/a/racz_m_1.atom2","atom")
newsfeed.addFeed("Avi Feller", "https://arxiv.org/a/feller_a_1.atom2","atom")
newsfeed.addFeed("Tom Berrett","https://arxiv.org/a/0000-0002-2005-110X.atom2","atom")
newsfeed.addFeed("Abhi Datta","http://arxiv.org/a/datta_a_2","atom")
newsfeed.addFeed("Jyotishka Datta","https://arxiv.org/a/datta_j_1.atom2","atom")
newsfeed.addFeed("Irina Gaynanova","https://arxiv.org/a/0000-0002-4116-0268.atom2","atom")
newsfeed.addFeed("Edward Kennedy","http://arxiv.org/a/kennedy_e_1.atom2","atom")
newsfeed.addFeed("Yang Ni","http://arxiv.org/a/ni_y_1.atom2","atom")
newsfeed.addFeed("Subhadeep Paul","https://arxiv.org/a/paul_s_3.atom2","atom")
newsfeed.addFeed("Mauricio Sadinle","http://arxiv.org/a/sadinle_m_1.atom","atom")
